### PR TITLE
Maximum likelihood for Rainbow

### PR DESCRIPTION
**Pull request by karpov-sv**
Switch Rainbow to maximum likelihood based cost function. It allows to correctly implement upper limits (using Tobit model for censored data) and additional barrier terms that would prevent the parameters from wandering too close to their limits (as then Hessian estimation would be wrong, giving extremely large errors, due to internal non-linear transformations of the parameters inside iminuit).
Improve initial values estimation and make them a bit more error-prone. 
Optimize some computations inside model function (`zeros_like` is much slower than plain `zeros`)
Also, slightly improve code readability by generalizing parameter unscaling. It allows to correctly return the covariance matrix.

### CODE REVIEW

**Review by hombit — APPROVED** [review]
Thank you, @karpov-sv, it looks really nice. I'd like @erusseil to review it before the merge.

@karpov-sv, do you think it may go to a patch (e.g. 0.9.4) release?

**Comment by karpov-sv** [comment]
> @karpov-sv, do you think it may go to a patch (e.g. 0.9.4) release?

Yes, it would be ok, as the code is declared experimental anyway. The changes from the point of view of "primary" API should be minimal (just a bit more stable).

**Review by erusseil — APPROVED** [review]
Thanks a lot Sergey for the work, it looks promising! I made some tests and everything appears very robust to me.

**Comment by hombit** [comment]
@karpov-sv @erusseil v0.9.4 has been released, and you both are now listed as co-authors of the package (as I should do earlier). Thank you!

**Pull request merged**
